server:
  port: ${PORT:9191}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgres
    url: "jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${DB_NAME:db_test}"
    username: "${DB_USERNAME:postgres}"
    password: "${DB_PASSWORD:taufan}"
    hikari:
      max-lifetime: "${DB_MAX_LIFE_TIME:240000}" # in milliseconds
      minimum-idle: "${DB_MIN_POOL:0}"
      maximum-pool-size: "${DB_MAX_POOL:5}"

    jpa:
      hibernate:
      ddl-auto: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
#      generate-ddl: true
      show-sql: "${SQL_SHOW_SQL:true}"
      properties:
        hibernate:
          format_sql: "${SQL_FORMAT_SQL:true}"

